pipeline {
    agent any

    tools {
        maven 'Maven'      // Jenkins Maven installation name
        jdk 'Java11'       // Jenkins JDK installation name
    }

    environment {
        GIT_URL        = 'https://github.com/shivashankarbukka402/Project.git'
        GIT_BRANCH     = 'main'
        GIT_CREDENTIALS = 'shivashankarbukka402'
        IMAGE_TAG = 'latest'
        DOCKERFILE_BASE = 'Dockerfile'
        DOCKER_REGISTRY_CRED_ID = 'docker_token'
        DOCKER_USER    = 'shiva9828'
        DOCKER_IMAGE   = 'shiva9828/devops-demo'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${env.GIT_BRANCH}",
                    credentialsId: "${env.GIT_CREDENTIALS}",
                    url: "${env.GIT_URL}"
            }
        }

       stage('Build with Maven') {
           steps {
                dir('devops-demo') {   // go inside folder where pom.xml exists
                     sh 'mvn clean install -DskipTests'
                }
           }
      }

      stage('Docker Build and Push') {
          steps {
                dir('devops-demo') {
                    sh 'sudo docker build -t shiva9828/devops-demo:latest .'
                    sh 'sudo docker push shiva9828/devops-demo:latest'
               }
          }
      }


        stage('Deploy to EC2') {
            steps {
                sshagent(['ec2-ssh-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ubuntu@<EC2_PUBLIC_IP> "
                        docker pull ${DOCKER_USER}/${DOCKER_IMAGE}:latest &&
                        docker stop demo || true &&
                        docker rm demo || true &&
                        docker run -d --name demo -p 8080:8080 ${DOCKER_USER}/${DOCKER_IMAGE}:latest
                        "
                    '''
                }
            }
        }
    }
}

